/*!
 * ParsleyJS-LaraExtras.js
 * Version ${pkg.version} - built ${now.format('ddd, MMM Do YYYY, h:mm a')}
 * hhttps://github.com/happyDemon/ParsleyJS-LaraExtras
 * Maxim Kerstens - <maxim.kerstens@gmail.com>
 * MIT Licensed
 */

// The source code below is generated by babel as
// ParsleyJS-LaraExtras is written in ECMAScript 6

